
# config.yaml

# ----------------- 目录配置 -----------------
# 原始数据文件所在的目录
RAW_DATA_DIR: raw_data/
# 清洗后数据输出的根目录
CLEANED_DATA_DIR: cleaned_data/
# 清洗后用于视图的CSV文件子目录
VIEW_DATA_SUBDIR: view/
# 清洗后OD对数据（已删除冗余）的CSV文件子目录
OD_DATA_SUBDIR: od_drop/
# 合并所有日期OD数据的输出文件名
ALL_WEEK_OD_FILENAME: all_week_od_data.csv


# ----------------- 数据列名映射配置 -----------------
# 将原始数据中的列名映射到代码中使用的通用列名。
# 例如： car_id: COMMADDR 表示原始数据中的 'COMMADDR' 列将被视为 'car_id'。
# 如果原始数据中的列名与通用列名相同，则无需在此处映射。
COLUMN_MAPPING:
  COMMADDR: car_id
  UTC: timestamp
  LON: longitude
  LAT: latitude
  TFLAG: status

# 原始数据中必需的列名 (用于初始加载时检查是否存在)
# 这些列名应该与 COLUMN_MAPPING 中映射的原始列名一致。
REQUIRED_RAW_COLS_FOR_CHECK:
  - COMMADDR
  - UTC
  - LON
  - LAT
  - TFLAG

# ----------------- OD识别参数配置 -----------------
# config.yaml
OD_CONFIG:
  min_trip_duration_sec: 30
  min_trip_distance_meter: 100
  tolerance_s: 3600
  tolerance_m: 500
  id_column: "car_id"
  time_column: "timestamp"
  longitude_column: "lon_gcj"
  latitude_column: "lat_gcj"
  status_column: "status"
  LOADED_STATUS: 268435456  # 新增
  EMPTY_STATUS: 0           # 新增

# ----------------- 数据过滤参数 -----------------
DATA_FILTER:
  MAX_SPEED_KMH: 120               # 最大允许速度(km/h)
  GEO_FENCE:                       # 地理围栏配置 (GCJ02坐标系下)
    CITY: "Jinan"                  # 城市名称更新为济南
    MIN_LON: 116.6                 # 济南市最小经度 (东经)
    MAX_LON: 117.3                 # 济南市最大经度 (东经)
    MIN_LAT: 36.6                  # 济南市最小纬度 (北纬)
    MAX_LAT: 37.2                  # 济南市最大纬度 (北纬)

# ----------------- 日志配置 -----------------
LOG_LEVEL: INFO # DEBUG, INFO, WARNING, ERROR, CRITICAL
LOG_FILE: pipeline.log
LOG_FORMAT: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# ----------------- OD 聚类参数配置 -----------------
OD_CLUSTERING:
  DBSCAN_EPS_DEG: 0.001       # DBSCAN的epsilon参数 (经纬度单位，约100米半径)
  DBSCAN_MIN_SAMPLES: 5       # DBSCAN的min_samples参数 (形成一个簇所需的最小样本数)
  HOTSPOT_OUTPUT_DIR: cleaned_data/hotspots/ # 聚类热力图输出目录
  TIME_BIN_INTERVAL_HOURS: 1  # 时间分箱间隔 (小时)
  
  # 用于批量处理OD文件的文件名前缀模式 (例如 'jn'，可选，如果文件夹内只有OD文件可留空)
  # 脚本将遍历 OD_DATA_SUBDIR 下所有符合 '_od_wh_drop.parquet' 模式的文件
  OD_FILE_PREFIX_PATTERN: jn